language: node_js

node_js:
  - 10.0.0

install:
  - npm install

script:
  - karma start --single-run

# 配置如下的内容，实现可以在 travis CI上打开Chrome来进行测试
addons:
  chrome: stable
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
